sudo: false

language: python

jobs:
  include:
    - python: 3.6
      dist: xenial
    - python: 3.7
      dist: bionic
    - python: 3.8-dev
      dist: bionic
  allow_failures:
    - python: 3.8-dev

install:
  - pip install poetry tox-travis

script:
  - tox

after_success:
  - codecov
