sudo: false

language: python

jobs:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8-dev
      dist: xenial
      sudo: true
  allow_failures:
    - python: 3.8-dev

install:
  - pip install pipenv
  - pip install codecov
  - pipenv install --dev --system

script:
  - nosetests tests --with-coverage --cover-package dataslots -cover-inclusive -v

after_success:
  - codecov
